default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: tubuyaku_development
test:
  <<: *default
  database: tubuyaku_test
production:
  <<: *default
  database: tubuyaku_production
  username: tubuyaku
  password: <%= ENV['TUBUYAKU_DATABASE_PASSWORD'] %>
